### PR TITLE
Favicon should work now

### PR DESCRIPTION
**Pull request by Mar10Josh**
I made bit changes, you can change it to this:
```html
<link rel="shortcut icon" href="data:image/x-icon;base64,AAABAAEAIB8AAAEAIAAkEAAAFgAAACgAAAAgAAAAPgAAAAEAIAAAAAAAgA8AACUWAAAlFgAAAAAAAAAAAAD8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//ySKP/8kif//JIn//ySKP/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyj//JIn//yTKf/8lzD//J5A//ykS//8pEv//J4///yWMP/8kyj//JIn//yTKP/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIn//yXMv/9rl7//s6e//7gwv/+6dT//uPI//7jyf/+6dT//t/A//7Mm//8rFr//Jcw//ySJ//8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMo//yUKv/9rV3//ty6///38P////////////7kyv/8oUX//KNJ//7p0//////////////37v/+2rX//atY//yTKf/8kyj//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKP/8lzH//cOI///16////////////////////////tKn//ySKf/8lCz//tm0////////////////////////8+f//b+B//yWL//8kyj//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyj//Jcx//7Mmv//+/j////////////////////////79//9tW3//JIm//ySJ//9u3j///36////////////////////////+vX//siR//yWL//8kyj//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yUK//9xIr///v3/////////////////////////////tq2//yZNv/8kyj//JIo//ycOv/+38D/////////////////////////////+vX//b+A//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kif//a5f///16/////////////////////////////7lzP/8okb//JIn//yTKf/8kyn//JIn//ylTf//6dT/////////////////////////////8ub//apX//ySJ//8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMo//yYNP/+3bz/////////////////////////////+PH//bFk//ySJv/8kyn//JMp//yTKf/8kyn//JIm//22b///+vX////////////////////////////+2bP//Jcw//yTKP/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kib//a9h///48v////////////////////////////7mzf/8mTX//JIn//ySJ//8kyn//JMp//ySJ//8kib//Jw7//7r1//////////////////////////////27f/9q1j//JIn//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yUKv/+0qX//////////////////////////////////t69//yWLv/9rV3//b5+//yWMP/8mDP//cCC//2qVv/8mDL//uPI//////////////////////////////////7Mmv/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyj//Jk1//7lzP/////////////////////////////////+17D//JUt//7XsP//8uX//J9B//yjSf//9uz//tCi//yWL//+3r7//////////////////////////////////uDC//yXMf/8kyj//JMp//yTKf/8kyn//JMp//ySJ//8oUX///Hj//////////////////////////////////7Wrf/8li7//tu5///16//8okf//KhS///58v/+1az//JYw//7dvP/////////////////////////////////+7dv//J4///ySKP/8kyn//JMp//yTKf/8kyn//JIm//2pVf//+PH//////////////////////////////////tq2//yYMv/+3bv///r0//2pVv/9sGL///36//7Xr//8mDP//uHD///////////////////////////////////17P/9pU3//JIn//yTKf/8kyn//JMp//yTKf/8kib//apX///58//////////////////////////////////+37///Jk2//7evv///fv//a9h//21bf///////tiy//yaN//+5Mr///////////////////////////////////bu//2mT//8kif//JMp//yTKf/8kyn//JMp//ySJ//9pk////Xs//////////////////////////////////7ixv/8mzn//t+////////9t3D//b5+///////+2bT//Jw6//7n0P//////////////////////////////////8ub//KJI//ySJ//8kyn//JMp//yTKf/8kyn//JIo//ydPP/+69j//////////////////////////////////ufQ//ydPv/+38D///////3Agv/9xo////////7atf/8n0H//uza//////////////////////////////////7nz//8mjf//JMo//yTKf/8kyn//JMp//yTKf/8kyn//JYv//7evf//////////////////////////////////7dz//KNJ//7hxP///////cWM//7LmP///////tu3//ylTP//8uX//////////////////////////////////tiz//yVLP/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kif//cGE///+/f/////////////////////////////06f/9rFr//ubN///////9y5n//tGk///////+38D//a5e///48P/////////////////////////////9+v/9vHr//JIn//yTKf/8kyn//JMp//yTKf/8kyn//JMp//ySJ//8okb//+/f//////////////////////////////n0//23cf/+6NL///////7RpP/+1q7///////7ix//9u3j///z5/////////////////////////////uvX//yfQP/8kij//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKv/9xo7///79/////////////////////////fz//cSK//7r1////////tWt//7atv///////ubM//3HkP/////////////////////////////9+//9wYT//JMo//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIo//ydPP/+4cT//////////////////////////v/+6tb///jx////////8OL///Ll////////9u7//uzZ/////////////////////////////t27//ybOP/8kij//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIn//2oU///69j///////////////////////////////////////////////////////////////////////////////////////7o0f/9pU3//JIn//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIo//2rWf/+6NH//////////////////////////////////////////////////////////////////////////v/+5cv//ahT//ySJ//8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIn//yjSP/+1a3///nz////////////////////////////////////////////////////////+PH//tKm//ygRP/8kif//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JIn//yWMP/9s2j//tiy///06f///Pn////////////////////+///8+f//8+f//tau//2xZP/8li7//JIn//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//ySJv/8li///KVO//20a//9xIv//s6d//7Nnf/9w4n//bNp//ykTP/8lS3//JIm//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kif//JEm//ySJ//8kif//JIn//ySJ//8kSb//JIn//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp//yTKf/8kyn//JMp/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" />
```

### CODE REVIEW

**Comment by R4356th** [comment]
Hi, the favicon already works and "shortcut" is ignored by browsers. I made a patch to fix this in Snap<i>!</i> a year ago.

**Comment by Mar10Josh** [comment]
> Hi, the favicon already works and "shortcut" is ignored by browsers. I made a patch to fix this in Snap! a year ago.

My browser just says no favicon.
Browser just shows gray earth

**Comment by R4356th** [comment]
Weird. It works for me on both Chrome and Firefox. Could you please open the browser console and tell me if there is anything there?

**Comment by Mar10Josh** [comment]
Screen Shot 2021-04-19 at 2 21 03 PM

**Reply to R4356th**
> Weird. It works for me on both Chrome and Firefox. Could you please open the browser console and tell me if there is anything there?

Nothing

**Comment by Daniel4-Scratch** [comment]
Might just be your browser

**Comment by Mar10Josh** [comment]
@R4356th i made an html file with it and it works.

**Comment by R4356th** [comment]
Implementing this change is an option, yes, but I do not understand why we should go with a hacky solution that is widely discouraged without further investigation. Someday, ``shortcut icon`` may even stop working. Could you please try clearing your browser cache and updating it if clearing cache does not work?

**Comment by Mar10Josh** [comment]
> Implementing this change is an option, yes, but I do not understand why we should go with a hacky solution that is widely discouraged without further investigation. Someday, `shortcut icon` may even stop working. Could you please try clearing your browser cache and updating it if clearing cache does not work?

I don't clear cache.
If I do some things (like saved things) will get deleted.

**Comment by R4356th** [comment]
> I don't clear cache.
> If I do some things (like saved things) will get deleted.

That is not what clearing cache does. Clearing cache just deletes files your browser stores locally on your computer to make browsing faster for you by showing the file from your computer rather than the server. If you do not want to clear cache, can you try visiting the SnapForks website in a private window, please?

**Comment by R4356th** [comment]
Mistakenly reopened...

**Pull request closed without merging**
