### PR TITLE
Modernize, clean up, and enhance code readability

### LINKED ISSUE #9: "#..." is Ignored
**Describe the bug**

**To Reproduce**
1. Use #something as a project name or author

**Expected behavior**
They should not be ignored.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest version
 - Version 1.0.0

**Additional context**
This is a HTML issue, I believe.
Edit by @Daniel4-Scratch: HTTPS/URL issue

### PR DESCRIPTION
**Pull request by icositetrachoron-programmer**
List of changes:

* Replaced `var` with `const`
* Replaced string concatenation with string interpolation using template literals
* Fixed #9 by URL encoding project name and author
* Created constants for each of the HTML elements that need to be used and used more meaningful variable and element IDs

### CODE REVIEW

**Comment by icositetrachoron-programmer** [comment]
List of changes:
* Replaced `var` with `const`
* replaced string concatenation with string interpolation using template literals
* Fixed #9 by URL encoding project name and author
* Created constants for each of the HTML elements that need to be used and used more meaningful variable and element IDs

**Review by R4356th — COMMENTED** [review]
While this LGTM, I do not think making variables constants or changing the way the code was before is necessary.

**Comment by Daniel4-Scratch** [comment]
Honestly this is kinda useless except for fixing the issue #9. And does it work?

**Comment by R4356th** [comment]
> And does it work?
Yes, you can view a live instance [here](https://mysterious-silver-script.glitch.me/).

**Comment by Daniel4-Scratch** [comment]
Hmm, I'll merge it thanks!

**Comment by Daniel4-Scratch** [comment]
Hmm, I'm afraid I'll need to revert that

**Pull request merged**
